from src import config

MODEL_NAME = config.MODEL_NAME
EPOCHS = config.EPOCHS
BATCH_SIZE = config.BATCH_SIZE
MAX_LEN = config.MAX_LEN
DATASET_PATH = config.DATASET_PATH
CHECKPOINT_DIR = config.CHECKPOINT_DIR
CONFIG_FILENAME = config.CONFIG_FILENAME